version: '3.1'

services:

  db:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nursery
    volumes:
      - ~/.docker-data/volumes/nursery:/var/lib/postgresql/data
    ports:
      - 15432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080