version: '3.1'

services:

  db:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nursery
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always